name: Deploy to OVH via FTP

on:
  push:
    branches:
      - main  # ou master selon ta branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm run build

      - name: Debug - Check secrets
        run: |
          echo "Checking FTP_SERVER..."
          if [ -z "${{ secrets.FTP_SERVER }}" ]; then
            echo "❌ FTP_SERVER is empty"
          else
            echo "✅ FTP_SERVER is set"
          fi
          
          echo "Checking FTP_USERNAME..."
          if [ -z "${{ secrets.FTP_USERNAME }}" ]; then
            echo "❌ FTP_USERNAME is empty"
          else
            echo "✅ FTP_USERNAME is set"
          fi
          
          echo "Checking FTP_PASSWORD..."
          if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
            echo "❌ FTP_PASSWORD is empty"
          else
            echo "✅ FTP_PASSWORD is set"
          fi

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./dist/
          server-dir: /www/
